services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    user: 1000:1000
    volumes:
      - ./src:/var/www
    ports:
      - '9000:9000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
  nginx:
    image: nginx:1.25
    container_name: nginx-app
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/public
    depends_on:
      - app
  node:
    image: node:16
    container_name: node-app
    working_dir: /var/www
    user: 'node'
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
